version: '3'
services:
  django:
    # container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;chmod +x ./docker-django-migrate.sh;sh ./docker-django-migrate.sh; python3 manage.py runserver 0.0.0.0:8000'
    volumes:
      - $PWD:/app
    env_file:
      - ./.env
    ports:
      - 8000:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
    networks:
        - webnetwork
    links:
        - db:db
    restart: always
  # angular
  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
      # - '49153:49153'
    volumes:
      # mount current src files
      - ./frontend:/app
      # exclude a subfolder
      - /app/node_modules/
      # exclude a file
      # - /dev/null:/app/Dockerfile
    command: ng serve --host 0.0.0.0 --disable-host-check
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    volumes:
      # - postgres_data:/var/lib/postgresql/data
      # - ./db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - webnetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
networks:
    webnetwork:
        driver: bridge
