CREATE ROLE django WITH LOGIN ENCRYPTED PASSWORD 'django';

CREATE DATABASE django WITH OWNER django ENCODING 'UTF8';

DROP DATABASE IF EXISTS django_db;
CREATE DATABASE django_db WITH OWNER django ENCODING 'UTF8';
